PyQt5 sinogram visualisation
UCL/STIR pull request #1059
Opened 2022-07-11 14:07 UTC by robbietuk

Sets up the basic PyQt5 UI and uses MatPlotLib for image show. Currently, takes command line argument for projection data path.

Remaining todo:

v0.2
- [x] File browser built into UI
- [x] Simplify UI layout. 
1. - [ ] Use pages to switch between `sinogram` and `viewgram`](https://realpython.com/python-pyqt-layout/#creating-a-stack-of-widgets)
2. - [ ] [Improve stretch](https://realpython.com/python-pyqt-layout/#managing-space-in-box-layouts)
- [x] Simplify controll (slider and scrollbox) backend
- [ ] Improve MatPlotLib visualisation interface OR use alternative libraries (_ABANDONED_)

v0.3
- [ ] Add 3D scanner view with 2D slice visualisation (_ABANDONED_)

--------
Development version screen share.

![image](https://user-images.githubusercontent.com/13292409/178544798-08fc578b-4e36-4eec-916d-93a8ed9f94cb.png)

2022-11-01 18:08 UTC, robbietuk commented
New updated version.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/13292409/199306368-24fbcb55-56c8-43fc-b1b2-cd64789e9e61.png">

This is probably the last mayor update I will do to this script. It is a useful tool IMO.

2022-11-01 18:25 UTC, KrisThielemans commented
Thanks! How would one run this from an existing python session, ideally with projection data already loaded?

2022-11-01 21:14 UTC, KrisThielemans requested changes
great thanks. one small request... Finally, can you add a line in release_5.1.htm? Then I'll leave you alone :-)

2022-11-01 21:14 UTC, KrisThielemans commented on examples/python/projdata_visualisation/ProjDataVisualisation.py
> +        gallery.set_projdata(projdata)
that's rather non-intuitive. I'd probably just remove the `filename` argument, or (probably better) do
```suggestion
def OpenProjDataVisualisation(projdata=None):
    app = QApplication([])
    gallery = ProjDataVisualisationWidgetGallery()
    
    if isinstance(projdata, str):
        gallery.load_projdata(projdata)
    elif  isinstance(projdata, str):
        gallery.set_projdata(projdata)
     elif projdata is not None:
       throw runtimeerrorsomehow
```

2022-11-01 21:14 UTC, KrisThielemans commented on examples/python/projdata_visualisation/ProjDataVisualisation.py
> +        gallery.set_projdata(projdata)
could also use a docstring if you don't mind.

2022-11-01 21:39 UTC, robbietuk commented
One moment before merge, fixing a bug.

2022-11-01 22:00 UTC, robbietuk commented
Done now. I fixed a bug if the filename was invalid. Rather than crash, it now reports it to the GUI.

2022-11-02 08:17 UTC, KrisThielemans approved these changes
thanks!
(no release notes, but I'll do that later)

2022-11-02 08:17 UTC, merged

2022-11-02 14:19 UTC, robbietuk commented
> thanks! (no release notes, but I'll do that later)

I see you have done that. Thank you. Hopefully it can be useful!