interpolate_axial: fixing rounding issue causing out of range
UCL/STIR pull request #1061
Opened 2022-07-26 15:15 UTC by danieldeidda

2022-07-26 17:24 UTC, KrisThielemans commented
I'm afraid I don't understand. Without `round` it is going to truncate (i.e. equivalent of `floor`). Is that really what you want?

With `round`, it is doing nearest neighbour interpolation I guess. With `floor`, it seems to me you could have half a plane offset. An alternative would be to use linear interpolation or overlap interpolation.

In any case, I think boundary conditions need to be handled separately.

2022-07-27 07:16 UTC, KrisThielemans commented
In fact, the use of offsets will be broken for blocksOnCylindrical with gaps in axial direction.

To implement nearest neighbour interpolation, I guess I'd do something like
1. construct `VectorWithOffset` with `m_in`
2. construct `VectorWithOffset` with `m_out`
3. for out_axial_pos: find closest `m_in`, and store corresponding sinogram

2022-07-27 08:18 UTC, danieldeidda commented
> I'm afraid I don't understand. Without `round` it is going to truncate (i.e. equivalent of `floor`). Is that really what you want?
> 

Yes that was what I wanted to do becaues the relative_pos needs to be within 0 to num_rings-1 and round would give me an index of 1 everytime the float part is >= .5;  But I was probably being naive, though I am not sure why the use of offset would be broken

2022-07-27 10:37 UTC, danieldeidda commented
> In fact, the use of offsets will be broken for blocksOnCylindrical with gaps in axial direction.
> 
> To implement nearest neighbour interpolation, I guess I'd do something like
> 
> 1. construct `VectorWithOffset` with `m_in`
> 2. construct `VectorWithOffset` with `m_out`
> 3. for out_axial_pos: find closest `m_in`, and store corresponding sinogram

OK but to find the the axial position we still need to apply the following no?
relative_pos=abs(((m -m_offset)/ m_sampling));

2022-07-27 16:37 UTC, KrisThielemans commented
> to find the the axial position we still need to apply the following no?
relative_pos=abs(((m -m_offset)/ m_sampling));

no. that would defeat the purpose. why not use `get_m(Bin(....,axial_pos,...))` to create the table I mentioned above?

2022-07-27 16:39 UTC, danieldeidda commented
yeah exactly.  now that i think about it the index of the m vector would actually correspond to the axial_position right?

2022-07-27 16:40 UTC, KrisThielemans commented
indeed!

2022-08-10 09:37 UTC, KrisThielemans requested changes

2022-08-10 09:37 UTC, KrisThielemans commented on src/buildblock/interpolate_axial_position.cxx
> +#endif
```suggestion
```
simpler and probably faster

2022-08-10 09:37 UTC, KrisThielemans commented on src/buildblock/interpolate_axial_position.cxx
> +#endif
```suggestion
```
simpler and probably faster

2022-08-10 09:37 UTC, KrisThielemans commented on src/buildblock/interpolate_axial_position.cxx
> +#endif
```suggestion
```
simpler and probably faster

2022-08-10 15:15 UTC, KrisThielemans requested changes
great. let's rename `relative_pos` to `sino_in` then, as that seems more logical.
Possibly also update the release notes?

2022-08-10 15:19 UTC, danieldeidda commented
mh we already have sino_in which is the input sinogram while relative_pos is an index:
sino_in=proj_data_in.get_sinogram(relative_pos,0);

2022-08-10 15:24 UTC, KrisThielemans commented
oops. `axial_pos_in`?

2022-08-10 15:31 UTC, danieldeidda commented
> but they seem to have gone now, which would be good 😄

ah OK glad they are gone 😆 
axial_pos_in sonds good

2022-08-10 16:45 UTC, KrisThielemans commented
great. should be good. Please add something to documentation/release_5.1.htm (with `[ci skip]`).

@emikhay this should be ready for testing now

2022-08-10 16:46 UTC, KrisThielemans commented
first 2 Appveyor jobs for previous commit were green. I've cancelled that job as it takes 2 hours, and just let the last one run.

2022-08-11 08:50 UTC, KrisThielemans commented
Great. I think we can merge this now as we know the current `master` is buggy anyway. @emikhay can then test from `master`.

@danieldeidda ok to squash merge?

2022-08-11 08:50 UTC, danieldeidda commented
yes fine for me!

2022-08-11 08:53 UTC, KrisThielemans approved these changes

2022-08-11 08:55 UTC, merged