Issue/1070 adding parallelproj tests
UCL/STIR pull request #1113
Opened 2022-12-16 14:00 UTC by markus-jehl

Added parallelproj tests to BlocksOnCylindrical tests, including a comparison between parallelproj and ray tracing on the projection of a single voxel.

2022-12-16 17:05 UTC, KrisThielemans requested changes
there's more here than I hoped, so I haven't reviewed this properly.

2022-12-16 17:05 UTC, KrisThielemans commented on src/recon_test/test_blocks_on_cylindrical_projectors.cxx
> +#include "stir/recon_buildblock/Parallelproj_projector/BackProjectorByBinParallelproj.h"
will have to be guarded by #ifdef

2022-12-16 17:05 UTC, KrisThielemans commented on src/recon_test/test_blocks_on_cylindrical_projectors.cxx
> +#include "stir/ProjDataInfoCylindrical.h"
implied by previous includes

2022-12-16 17:23 UTC, markus-jehl commented
Daniel's tests I only modified in that I introduced the templates and reordered them to be consistently ordered, because I was getting a bit confused which one was which. So the only real changes are the templates and the new test.

2022-12-17 08:11 UTC, KrisThielemans reviewed
looks fine, and checks work!

I'm not sure though why you templated all functions in the projector type. As far as I can see, using a `shared_ptr<ForwardProjectorByBin>` would work as well. No templating required. Feel like changing that?

(In fact,there's no reason here to pass a `shared_ptr` and using `ForwardProjectorByBin&` would be slightly better class design here, but that kind of stuff doesn't matter in the test of course).

2022-12-19 09:06 UTC, markus-jehl commented
True, didn't think of that! Let me change that quickly.

2022-12-19 13:13 UTC, markus-jehl commented
Some images to illustrate results of projections (left: ray tracing; right: parallelproj)
![image](https://user-images.githubusercontent.com/87262701/208433712-a10d366d-c5a5-4b5c-932e-a18e7cf2baf9.png)
![image](https://user-images.githubusercontent.com/87262701/208433845-584817de-f1b6-4c2a-a46b-c6ae4216ea6b.png)
![image](https://user-images.githubusercontent.com/87262701/208433876-a34ab6b2-270a-4621-b0e5-ade344b790f5.png)
voxel
![image](https://user-images.githubusercontent.com/87262701/208433994-f5f83a33-c18f-43df-999b-1f2921f25195.png)

2022-12-19 14:17 UTC, KrisThielemans commented
Excellent. Thanks!

There's also `test_view_offset_root.cxx` but feel free to decline fixing that now. (It's more important for the TOF branch later, so we could do that then).

2022-12-19 14:56 UTC, markus-jehl commented
That doesn't seem to use projectors, but work straight on `ProjMatrixByBinUsingRayTracing`. I wouldn't know how to test this with parallelproj without digging into the code for a bit (or you telling me ;-) ).

2022-12-19 15:14 UTC, danieldeidda approved these changes
looks good

2022-12-19 15:33 UTC, merged