adding utility that extracts interfile+binary from SPECT dicom data
UCL/STIR pull request #1122
Opened 2023-01-04 11:22 UTC by danieldeidda

2023-03-06 15:59 UTC, KrisThielemans requested changes
will need to add it to release notes

2023-03-06 15:59 UTC, KrisThielemans commented on src/utilities/CMakeLists.txt
> +        SPECT_dicom_to_interfile.cxx
probably within `HAVE_ITK` or so

2023-03-06 15:59 UTC, KrisThielemans commented on src/utilities/SPECT_dicom_to_interfile.cxx
> +#include <iostream>
add usual copyright header

2023-03-31 12:35 UTC, KrisThielemans commented
@danieldeidda how does this handle multiple energy window data. Is there one DICOM file per energy window?

2023-03-31 13:33 UTC, danieldeidda commented
I have never seen a case with multiple energy windows data in the same file in our case we usually have different dicom files but I am pretty sure the dicom file has the information if the acquisition was performed with multiple energy windows

2023-04-08 13:29 UTC, KrisThielemans commented
Replaced by #1182

2023-04-08 13:29 UTC, closed without merging