making ECAT8 LM input file format specific to siemens ecat8
UCL/STIR pull request #1208
Opened 2023-05-24 10:58 UTC by danieldeidda

2023-05-24 10:59 UTC, danieldeidda commented
This has been tested on the mMR data from zenodo

2023-05-25 00:14 UTC, KrisThielemans requested changes
I'd prefer to do the check on `is_interfile_signature` first (i.e. if that fails, get out immediatelly).

Currently our `FileSignature` size is 1024. I looked at one of your mCT files
```
**!INTERFILE :=
!originating system :=1104
%comment:=Bin Address SubHeader for PETSYNGO_VG70B
%SMS-MI header name space :=PETLINK bin address
%SMS-MI version number :=3.7
```
So I guess it still fits in there. Can you check with that as well? (Obviously, it won't be able to read it due to header problems etc, but we should get into the parsing)

2023-05-25 00:14 UTC, KrisThielemans commented on src/include/stir/IO/ECAT8_32bitListmodeInputFileFormat.h
> +    for (int i=0;i<signature.size(); i++)
This would have to be `signature.size()-8` to avoid buffer-overrun.

2023-05-25 00:14 UTC, KrisThielemans commented on src/include/stir/IO/ECAT8_32bitListmodeInputFileFormat.h
> +                std::string(1,signature.get_signature()[i+6]);
```suggestion
        const std::string ecat8(signature.get_signature() + i, 8);
```
should work I believe

2023-05-25 00:21 UTC, KrisThielemans commented
Actually, the following might be faster
```
const std::string signature_as_string(signature.get_signature(), signature.size());
return signature_as_string.find("PETLINK") != std::string::npos;
```

2023-05-25 09:42 UTC, danieldeidda commented
> So I guess it still fits in there. Can you check with that as well? (Obviously, it won't be able to read it due to header problems etc, but we should get into the parsing)

yes it parses this too

2023-05-25 10:33 UTC, KrisThielemans commented on src/include/stir/IO/ECAT8_32bitListmodeInputFileFormat.h
> +        }
```suggestion
        else
        {
            for (int i=0;i<signature.size()-8; i++)
            {
                const std::string signature_as_string(signature.get_signature(), signature.size());
                return signature_as_string.find("PETLINK") != std::string::npos;
            }
        }
```

2023-05-25 10:33 UTC, KrisThielemans commented on src/include/stir/IO/ECAT8_32bitListmodeInputFileFormat.h
> +        }
no more need for the loop now!

2023-05-25 10:38 UTC, danieldeidda commented on src/include/stir/IO/ECAT8_32bitListmodeInputFileFormat.h
> +        }
of course :D

2023-05-25 10:43 UTC, KrisThielemans approved these changes
seems fine to me now. Does it still work on the data?

2023-05-25 13:32 UTC, danieldeidda commented
yes it does!

2023-05-25 13:35 UTC, merged