SPECTUB: initilising old global values fixing #1232
UCL/STIR pull request #1244
Opened 2023-09-08 15:21 UTC by danieldeidda

2023-09-08 15:56 UTC, KrisThielemans requested changes
looks good. some comments on clean-up.

Did you run this through `valgrind`?

2023-09-08 15:56 UTC, KrisThielemans commented on src/recon_buildblock/ProjMatrixByBinSPECTUB.cxx
> +      wmh.COL.do_fb = false;
```suggestion
      // no fan-beam
      wmh.COL.do_fb = false;
      // code to enable fan-beam collimator at some point... (not validated)
      // before enabling, you will have to change the parameter file to give parameters of the fan-beam
      // wmh.COL.do_fb = true;
      // wmh.COL.F     = collimator_number;
```

2023-09-08 15:56 UTC, KrisThielemans commented on src/recon_buildblock/ProjMatrixByBinSPECTUB.cxx
> +      //if ( num ==0 ) {
```suggestion
      //if (wmh.COL.do_fb ==0 ) {
```

2023-09-08 15:56 UTC, KrisThielemans commented
@samdporter please take a look and try

2023-09-11 09:34 UTC, samdporter commented
> @samdporter please take a look and try

Looks good to me!

Tested with STIR & SIRF

2023-09-11 10:26 UTC, KrisThielemans commented
Thanks @samdporter. 'valgrind' as well?

2023-09-11 10:58 UTC, samdporter commented
> Thanks @samdporter. 'valgrind' as well?

Looks fine to me. Updated the valgrind output files [here](https://github.com/samdporter/SPECTissues)

2023-09-11 16:05 UTC, KrisThielemans commented
Can either of you look at my comments please? Would like to merge this soon

2023-09-12 20:57 UTC, KrisThielemans approved these changes

2023-09-12 20:57 UTC, merged