ProjData Visualisation window improvement and segment num bug fix
UCL/STIR pull request #1321
Opened 2024-01-11 18:52 UTC by robbietuk

## Changes in this pull request
Fixes a bug with the `segment_num` parameter not being used in the method, instead it was using an internal call to `self.get_current_segment_num()`. This limited the method to the current state of the data, rather than the abstract.

## Testing performed
Yes

## Related issues

As mentioned: https://github.com/UCL/STIR/pull/1319#issuecomment-1887685739

## Checklist before requesting a review

  - [] I have performed a self-review of my code
  - [] I have added docstrings/doxygen in line with the guidance in the developer guide
  - [] I have implemented unit tests that cover any new or modified functionality (if applicable)
  - [] The code builds and runs on my machine
  - [] `documentation/release_XXX.md` has been updated with any functionality change (if applicable)

2024-01-11 21:16 UTC, robbietuk commented
I have tested this for non-TOF sinogram data, everything seems okay. @KrisThielemans or @NicoleJurjew, could you please test for TOF data? I don't have any accessible right now.

P.S. We need some example TOF data?

2024-01-11 21:59 UTC, KrisThielemans commented
If you run recon_test_pack/run_test_listmode_recon.sh,  you'll have some (but needs ROOT)

2024-01-11 22:24 UTC, KrisThielemans requested changes
also 2 Codacy items

2024-01-11 22:24 UTC, KrisThielemans commented on examples/python/projdata_visualisation/BackendTools/STIRInterface.py
> +            return False
I think this needs to be
```python
 if filename is None or filename == "":
       return False

  self.projdata_filename = filename
```

2024-01-11 22:24 UTC, KrisThielemans commented on examples/python/projdata_visualisation/BackendTools/STIRInterface.py
> +        self.segment_data = self.projdata.get_segment_by_view(stir.SegmentIndices(segment_number, timing_pos))
looks like you can run you `get_segment_data` function

2024-01-11 22:24 UTC, KrisThielemans commented on examples/python/projdata_visualisation/BackendTools/UIGroupboxProjdataDimensions.py
> +            if (view_num_limits[0] - view_num_limits[1]) != 0:
fancy way if saying they're not equal... why not say `limits[1]>limits[0]`?

2024-01-12 03:14 UTC, robbietuk commented
I think there was a bug in #1319. When changing the TOF Bin slider, I am getting the same imaging (I think).
Adding a print statement to `timing_pos_refresh`:
```
    def timing_pos_refresh(self):
        """This function is called when the user changes the TOF bin value."""
        new_segment_num = self.UI_slider_spinboxes[ProjDataDims.SEGMENT_NUM].value()
        new_timing_pos = self.UI_slider_spinboxes[ProjDataDims.TIMING_POS].value()
        self.stir_interface.segment_data = self.stir_interface.get_segment_data(new_segment_num, new_timing_pos)
        print(f"TOF bin changed to {new_timing_pos}, "
              f"segment data has tof pos number: {self.stir_interface.segment_data.get_timing_pos_num()}")
        self.UI_controller_UI_change_trigger()
```
Console log:
```
TOF bin changed to -2, segment data has tof pos number: 0
```
This is calling
```
    def get_segment_data(self, segment_number=0, timing_pos=0) -> stir.FloatSegmentByView:
        """Returns the segment data."""
        return self.projdata.get_segment_by_view(stir.SegmentIndices(segment_number, timing_pos))
```
Something is going wrong on the CPP level. `get_segment_by_view` is defined here:
https://github.com/UCL/STIR/blob/151c457495721d38e1c3f00780a81055735bacb3/src/buildblock/ProjData.cxx#L409-L417

2024-01-12 07:46 UTC, KrisThielemans commented
#1319 fixed a bug in `ProjData::get_segment_by_view(SegmentIndices&)`. The relevant line is now
https://github.com/UCL/STIR/blob/151c457495721d38e1c3f00780a81055735bacb3/src/include/stir/ProjData.inl#L30
while it didn't have pass `timing_pos` through before.

Are you sure you recompiled? It does change the TOF Data for me (after that fix)

2024-01-12 17:21 UTC, robbietuk commented
> Are you sure you recompiled? It does change the TOF Data for me (after that fix)

I had recompiled but VSCode was not loading my .bash_profile with the updated install directory in the `$PYTHONPATH`. No wonder my debugging was failing.


I think that should do it. I changed more than I would like but the code probably needs a bit more with some improvements to the PyQt5 usage.

Once codacy has completed we can squash merge. You can use the details in the initial summary https://github.com/UCL/STIR/pull/1321#issue-2077383886

2024-01-12 17:24 UTC, KrisThielemans approved these changes
I haven't tried it myself yet, but favour merging ASAP. Thanks!

2024-01-12 17:26 UTC, merged