Create empty interfile binary utility
UCL/STIR pull request #1351
Opened 2024-01-29 22:27 UTC by robbietuk

I was playing around and created this. I don't believe STIR has anything like this but let me know if it is useful or not.

## Changes in this pull request

Adds `create_empty_interfile_binary` utility that takes an interfile header and create a corresponding binary file on the system.
```bash
create_empty_interfile_binary header_filename [fill_value]
```
Given a valid Interfile format header, this utility will create a binary file for the header. The optional `fill_value` argument will fill the binary file with the specified value. If no `fill_value` is specified, the binary file will be filled with zeros.

This utility is used when a header file, with no corresponding binary is provided. This utility is to assist with collaborative development. For example, if a user experiences an issues with STIR, the only the header file needs to be transferred to others for debugging.

This utility will not overwrite existing binary files.

Currently, requires header file to have a valid extension (.hs or .hv) to determine the type of data.

## Testing performed
Current CTests

## Checklist before requesting a review

  - [ ] I have performed a self-review of my code
  - [ ] I have added docstrings/doxygen in line with the guidance in the developer guide
  - [ ] I have implemented unit tests that cover any new or modified functionality (if applicable)
  - [ ] The code builds and runs on my machine
  - [ ] `documentation/release_XXX.md` has been updated with any functionality change (if applicable)

2024-01-30 09:53 UTC, KrisThielemans requested changes
I'm not 100% sure how useful this is, but I don't mind adding it. It'd have to be in the Users guide as well I guess.

weirdly, almost everything on the projection data side can be done with other types as well (i.e. it doesn't need an interfile header), but it's fine to leave it as-is.

2024-01-30 09:53 UTC, KrisThielemans commented on src/utilities/create_empty_interfile_binary.cxx
> +  Copyright (C) 2024, Prescient Imaging # TODO: CONFIRM?
ah well. it's time to sort this out, yes

2024-01-30 09:53 UTC, KrisThielemans commented on src/IO/interfile.cxx
> +create_image_from_header(stir::InterfileImageHeader& hdr)
no particular reason to have `stir::` here

2024-01-30 09:53 UTC, KrisThielemans commented on src/IO/interfile.cxx
> +  const BasicCoordinate<3,int> max_indices = min_indices + make_coordinate(z_size, y_size, x_size) - 1;
I prefer to avoid changes like this, even when suggested by our clang-format. We will do all of them in one swoop.

2024-01-30 09:53 UTC, KrisThielemans commented on src/utilities/create_empty_interfile_binary.cxx
> +create_empty_projdata_interfile_binary(char* header_file, float fill_value)
let's avoid `char *`

2024-02-14 19:53 UTC, robbietuk commented
> I'm not 100% sure how useful this is, but I don't mind adding it. It'd have to be in the Users guide as well I guess.

Upon some time and review, I agree. I'll happily leave it open in draft or just close it.

2024-02-15 23:57 UTC, KrisThielemans commented
I'll close this then, as the code-base is already large enough 😄

2024-02-15 23:57 UTC, closed without merging