use listmode time frame for output frame definition if all events are used
UCL/STIR pull request #1519
Opened 2024-10-02 14:52 UTC by danieldeidda

use interfile information for frame difinition if all event are used,… throwing a warning otherwise

## Changes in this pull request
use interfile information for frame difinition if all event are used,… throwing a warning otherwise

## Testing performed
yes

## Related issues
--fixes #1512   

## Checklist before requesting a review

  - [v] I have performed a self-review of my code
  - [] I have added docstrings/doxygen in line with the guidance in the developer guide
  - [] I have implemented unit tests that cover any new or modified functionality (if applicable)
  - [v] The code builds and runs on my machine
  - [] `documentation/release_XXX.md` has been updated with any functionality change (if applicable)

2024-10-03 10:02 UTC, KrisThielemans commented on src/listmode_buildblock/LmToProjData.cxx
> +          warning("A sub-sumple of the total events has been selected. The frame duration will be incorrect");
```suggestion
          warning("LmToProjData: num_events_to_store has been selected. The frame duration in the Interfile header will be incorrect!");
```

2024-10-03 13:13 UTC, KrisThielemans commented
most jobs were ok, but one
https://github.com/UCL/STIR/pull/1519/checks#step:17:1059
can you check the log file (downloadable from the Actions page).

Also, clang-format issues.

2024-10-03 16:37 UTC, KrisThielemans commented
Can be reproduced by using the following .par file
```
lm to projdata parameters :=
input file := root_header.hroot
template projdata := template_for_ROOT_scanner.hs
frame definition file :=
num events to store := 0
output filename prefix := my_sinogram_counts_TOF

maximum absolute segment number to process := 3
do pre normalisation := 0
num tof bins in memory := 5
num segments in memory := 7
store prompts := 1
store delayeds := 0
list event coordinates := 0
end :=
```
and
```
INPUT_ROOT_FILE=test_PET_GATE.root lm_to_projdata my_lm_to_projdata_counts_TOF.par
```
which results in
```
Last stored event was recorded before time-tick at 0 secs
Total number of counts (either prompts/trues/delayeds) stored: 0
```
This is probably due to the fact that the `.hroot` file does not contain any time info, so we might need to check if the time from th elm file is valid or not.

2024-11-18 16:19 UTC, KrisThielemans commented on src/listmode_buildblock/LmToProjData.cxx
> +      frame_defs = lm_data_ptr->get_exam_info_sptr()->get_time_frame_definitions();
```suggestion
      frame_defs = lm_data_ptr->get_exam_info_sptr()->get_time_frame_definitions();
      if (frame_defs.get_num_time_frames() == 0)
        {
          vector<pair<double, double>> frame_times(1, pair<double, double>(0, 0));
          frame_defs = TimeFrameDefinitions(frame_times);
        }
```

2024-11-18 17:09 UTC, KrisThielemans requested changes

2024-11-18 17:09 UTC, KrisThielemans commented on documentation/release_6.3.htm
> +    <a href=https://github.com/UCL/STIR/pull/1519>PR #1503</a>
This should remain 1503

2024-11-18 17:09 UTC, KrisThielemans commented on documentation/release_6.3.htm
> +    <a href=https://github.com/UCL/STIR/pull/1503>PR #1503</a>
This has to be 1519. Also, please use ROOT, use `<tt>lm_to_projdata</tt>` and put a `<br>` after that line.

2024-11-18 17:16 UTC, danieldeidda commented on documentation/release_6.3.htm
> +    <a href=https://github.com/UCL/STIR/pull/1519>PR #1503</a>
sorry I changed the wrong one

2024-11-19 15:52 UTC, KrisThielemans approved these changes
thanks! squash-merge ok here? (we went back-and-forth a bit).

2024-11-19 16:38 UTC, danieldeidda commented
> thanks! squash-merge ok here? (we went back-and-forth a bit).

sure

2024-11-19 17:20 UTC, merged