Expose current_time in LmToProjData.
UCL/STIR pull request #1525
Opened 2024-10-17 12:28 UTC by markus-jehl

## Changes in this pull request
Expose current_time in LmToProjData

## Testing performed

## Related issues
Fixes https://github.com/UCL/STIR/issues/1523

## Checklist before requesting a review

  - [x] I have performed a self-review of my code
  - [] I have added docstrings/doxygen in line with the guidance in the developer guide
  - [] I have implemented unit tests that cover any new or modified functionality (if applicable)
  - [x] The code builds and runs on my machine
  - [] `documentation/release_XXX.md` has been updated with any functionality change (if applicable)

2024-10-17 20:55 UTC, KrisThielemans commented
simple enough, but the name is probably confusing (it isn't the "current time" as far as LmToProjData goes). Maybe `get_last_processed_lm_rel_time()` or something like that?

2024-10-18 10:08 UTC, markus-jehl commented
> simple enough, but the name is probably confusing (it isn't the "current time" as far as LmToProjData goes). Maybe `get_last_processed_lm_rel_time()` or something like that?

That make sense! Renamed it.

2024-10-18 17:53 UTC, KrisThielemans requested changes
ok, now please add a doxygne comment to the new function, sorry. i'll then squash-merge.

2024-10-21 00:12 UTC, KrisThielemans commented on src/include/stir/listmode/LmToProjData.h
> +  /* For most listmode formats, this is equivalent to the acquisition duraiton in seconds */
```suggestion
  /*! This can be used to find the duration (in seconds) of the last time frame processed. */
```

2024-10-21 00:13 UTC, KrisThielemans approved these changes

2024-10-21 00:15 UTC, merged