Scatter forward projector setter
UCL/STIR pull request #1530
Opened 2024-10-28 19:42 UTC by robbietuk

## Changes in this pull request

Introduces the ability to set and retrieve a forward projector for scatter estimation, used in mask forward projection, in the ScatterEstimation class. Also adds a keymap parser.

## Related issues

Fixes #1527

## Checklist before requesting a review

  - [x] I have performed a self-review of my code
  - [x] I have added docstrings/doxygen in line with the guidance in the developer guide
  - [] I have implemented unit tests that cover any new or modified functionality (if applicable)
  - [x] The code builds and runs on my machine
  - [] `documentation/release_XXX.md` has been updated with any functionality change (if applicable)

2024-11-02 02:44 UTC, robbietuk commented
Ready to merge.

2024-11-25 16:56 UTC, KrisThielemans requested changes

2024-11-25 16:56 UTC, KrisThielemans commented on src/include/stir/scatter/ScatterEstimation.h
> +#include <stir/recon_buildblock/ForwardProjectorByBin.h>
```suggestion
#include "stir/recon_buildblock/ForwardProjectorByBin.h"
```

2024-11-25 16:56 UTC, KrisThielemans commented on src/include/stir/scatter/ScatterEstimation.h
> +  shared_ptr<ForwardProjectorByBin> get_forward_projector_sptr() const;
need to change naming. These are currently only used for the sino mask generation. Maybe `....forward_projector_for_mask...`?

2024-11-25 16:56 UTC, KrisThielemans commented on src/include/stir/scatter/ScatterEstimation.h
> +  shared_ptr<ForwardProjectorByBin> forward_projector_sptr;
name here as well

2024-11-25 16:56 UTC, KrisThielemans commented on src/scatter_buildblock/ScatterEstimation.cxx
> +  this->parser.add_parsing_key("forward projector type", &this->forward_projector_sptr);
and here

2024-11-27 21:09 UTC, KrisThielemans approved these changes

2024-11-27 21:11 UTC, KrisThielemans commented
ah, sorry, can you add a line to `release_6.3.htm` please? (include `[ci skip]` in the commit, as it seems our "exclude `*htm` doesn't work for GitHub Actions)

2024-11-27 21:11 UTC, KrisThielemans commented
I'll squash-merge if ok

2024-11-27 22:24 UTC, KrisThielemans commented
looks like there's a conflict with `master` in the release notes...

2024-11-27 23:21 UTC, merged