SSRB can take an template sinogram
UCL/STIR pull request #708
Opened 2020-10-08 19:52 UTC by robbietuk

The SSRB utility currently only allows for axial compression of needs to be an odd number (`ERROR: SSRB: num_segments_to_combine (2) needs to be odd`). However, this does not allow us to create `span-2` sinograms. This PR allows for the `--template` flag to be used on the command line instead of providing other the standard arguments.

- [x] Does this work? 
I can convert span-1 sinograms to span-2
- [ ] Documentation and usage update
- [ ] Cleanup the previous argument methodology. This worked before but it probably isnt very clean now. I think these two input methods should be different functions and handle the input arguments differently.

2020-10-08 20:24 UTC, KrisThielemans requested changes
a few suggestions. Once we're happy, we need to update the Usage message (best to put it in a `static void print_usage_and_exit(const std::string& prog_name)` as in many other STIR utilities including `zoom_image`), doxygen header, and add something to `release_5.htm`.

By the way, I'd take the opportunity to rename `span` to `num_segments_to_combine`, as that's what it is (input doesn't have to be `span=1`)

2020-10-08 20:24 UTC, KrisThielemans commented on src/utilities/SSRB.cxx
> +#include <stir/ProjDataInterfile.h>
```suggestion
#include "stir/ProjDataInterfile.h"
```
it isn't a system file.

2020-10-08 20:24 UTC, KrisThielemans commented on src/utilities/SSRB.cxx
> +  if (strcmp(argv[3], "--template")==0)
please follow same conventions as `zoom_image`, i.e. all options upfront, and hence `SSRB --template bla output input`.

Also, will need to check if `argc` is appropriate for this signature.

2020-10-09 12:39 UTC, robbietuk commented
`main` was getting a little busy, there was little overlap between the new `template_based_SSRB` and `classical_SSRB`, so I split them into two functions to make it clearer. I am not set on the function names, feel free to suggest others. 

I have tested this on D690 sinograms, converting span-1 to span-2. Previously this would have been impossible as `num_segments_to_combine=2` would have errored.

2020-10-09 14:00 UTC, KrisThielemans requested changes
tiny doc changes

2020-10-09 15:40 UTC, robbietuk commented
Ready for squash merge

2020-10-09 19:27 UTC, merged