Test
UCL/STIR pull request #833
Opened 2021-02-24 06:42 UTC by gefeichen

![normfile](https://user-images.githubusercontent.com/32598440/108958110-763c1180-76ad-11eb-8def-370a5dfee872.png)
I got it by dividing normalized projdata by raw projdata (mCT).
And no zero value found in https://github.com/UCL/STIR/blob/882c261bc23af642865e61f00b19d902dcf3a5f3/src/utilities/find_ML_normfactors3D.cxx#L162 after make_fan_data_remove_gaps

2021-02-24 07:19 UTC, gefeichen commented
![sinogram after norm](https://user-images.githubusercontent.com/32598440/108962268-77703d00-76b3-11eb-91f2-335b76deee3c.png)
And another image:  upper is a cylinder sinogram, below is a sinogram after normalisation

2021-02-24 07:59 UTC, KrisThielemans requested changes
This looks very nice to me.  Thanks a lot.

I have 2 suggestions in the review below. In addition, I think we should get rid of the old `make_fan_data` and its inverse. Otherwise we keep too much code duplication.

Add yourself as author and whoever owns your copyright in the headers. Also, add a note in release_5.0.htm in section `changed functionality`.

2021-02-24 07:59 UTC, KrisThielemans commented on src/buildblock/ML_norm.cxx
> +    const int num_physical_axial_crystals_per_block = num_axial_crystals_per_block - virtual_axial_crystals;
I guess we could just as well provide the member functions for these 2 as well.

2021-02-24 07:59 UTC, KrisThielemans commented on src/buildblock/ML_norm.cxx
> +                    (*segment_ptr)[bin.axial_pos_num()][bin.view_num()][bin.tangential_pos_num()] = 0;
I suggest we use an extra input argument to the function `gap_value`, defaulting to 0. It will also make it clearer what's happening here.

2021-02-24 08:01 UTC, KrisThielemans commented
I believe this supersedes your other PR. If so, please close it by referring to this one.

I don't understand the first picture. Can you provide a bit more detail?

2021-02-24 08:21 UTC, gefeichen commented
> I believe this supersedes your other PR. If so, please close it by referring to this one.
> 
> I don't understand the first picture. Can you provide a bit more detail?

I used a cylinder source in gPET to cover the whole FOV and generated corresponding model projection data.

It's hard to visualize the norm parameter. So I just use manip_segments to divide model_data by measure_data.  And the result shows in the first picture. Maybe it's useless.

2021-02-24 08:25 UTC, KrisThielemans commented
easier to look at the inverse of it:
```
stir_math -s --including-first --power -1 eff_factors.hs norm_factors.hs
```
could do the trick

2021-02-24 08:29 UTC, KrisThielemans commented
I'd also compare measured data with model*eff_factors. I think you get the latter with `apply_normfactors3D` with `apply_or_undo=1`.

2021-02-24 09:44 UTC, gefeichen commented
The absolute difference of measure and model*eff_factors is 19%
`sum(abs(model*eff-measure))/sum(measure)`
I don't know whether it is correct.

Below is eff and geo factors. left:eff   right:geo
![normeffgeo](https://user-images.githubusercontent.com/32598440/108981538-c9bb5900-76c7-11eb-9b9b-38b4cfb72543.png)

2021-02-24 10:29 UTC, KrisThielemans commented
> The absolute difference of measure and model*eff_factors is 19%

they will be different because of noise of course. Hard to quantify that. But 19% doesn't look too bad. efficiencies look a bit strange but could be alright.

I note that my text was confusing. with "eff_factors" I meant "eff*geo" (i.e. the total efficiency, also known as "1/norm_factors"). I'll call them "total_eff_factors" below.

Things to compare measured with model*total_eff_factors:
- visual comparison of 
- profiles. you will probably have to do some averaging to reduce noise.
- reconstruction of the gate data used for normalisation (`lm_to_projdata` with excluding scatters and randoms, no background in recon).
- reconstruction of other gate data  (`lm_to_projdata` with excluding scatters and randoms, no background in recon).
- reconstruction of other gate data full pipeline (although that doesn't have anything to do with the norm)

Are you using https://github.com/UCL/STIR-GATE-Connection? If so, it tells you how to handle the norm (currently `BinNormalisationFromProjData` needs the norm-factors, not the total_eff_factors)

2021-02-24 10:33 UTC, KrisThielemans requested changes
can you merge `master` in here to resolve the conflict? sorry.

2021-02-24 10:33 UTC, KrisThielemans commented on src/buildblock/ML_norm.cxx
> +                  const FanProjData& fan_data, const int gap_value)
` float`  please

2021-02-24 10:33 UTC, KrisThielemans commented on src/include/stir/ML_norm.h
> +                  const int gap_value=0);
```suggestion
                  const float gap_value=0.F);
```

2021-03-01 09:22 UTC, KrisThielemans approved these changes

2021-03-02 18:41 UTC, KrisThielemans commented
@gefeichen, will your mCT tests be affected by #838 and/or #837?

2021-03-07 03:00 UTC, NikEfth commented
Hi , I am sorry for the delay, I will test with my data tonight.

2021-03-15 14:41 UTC, NikEfth reviewed
Hi @gefeichen 
Thank you for your good work, 
I don't have mCT data but from my data (which as we had discussed are slightly different ) (and your code) I saw that the last segment was coming out empty. 
I don't think that this actually has to do with your modifications but, could you please check you last, and second to last segments?  I believe that those would be +54 and +53 (?), might be wrong, though.

2021-03-15 14:41 UTC, NikEfth commented on src/buildblock/ML_norm.cxx
> +    const int num_physical_rings = num_rings - (num_axial_blocks-1)*virtual_axial_crystals;
I agree with this.

2021-03-16 06:46 UTC, gefeichen commented
Hi @NikEfth 
   Thanks for your checking.
   Could you provide more information about your data? Like ring numbers, virtual crystal number, and position

2021-09-22 19:15 UTC, KrisThielemans commented
This seems ready to me now, and we have the signed letter.

@NikEfth if you have any final comments, let us know. Otherwise I'll merge

2021-09-24 12:20 UTC, merged