Demo5 - gradient line search
UCL/STIR pull request #896
Opened 2021-05-26 19:10 UTC by robbietuk

A piece of code I developed for my own research that adds the ability to perform a line search in C++ using STIR. I feel this is a natural progression from `demo4_obj_fun.cxx` to do something that is optimisation based but not already in STIR.

From the file brief:
A class to compute a line search evaluation in the direction of the gradient of a given image and objective function. All parameters can be parsed from a parameter file. See `demo5_line_search.par`.

Give an image and objective function configuration, this script will perform a line searchfrom an minimum to an maximum step size (alpha). Options are included to perform this line search linearly or using exponential step
size iterations. Additionally, a lower positivity bound is applied to all computed image.

The results are saved to files: `alphas.dat` contains the step size values investigated, and `Phis.dat` contains the objective function evaluations. Furthermore, the image corresponding to the maximum objective function and the gradient used in the line search are saved to file.

2021-05-26 21:23 UTC, robbietuk reviewed
Also need some way for travis to test #889

2021-05-26 21:23 UTC, robbietuk commented on examples/C++/src/demo5_line_search.par
> +    image filename :=
Should provide image (from another demo)

2021-05-26 21:23 UTC, robbietuk commented on examples/C++/src/demo5_line_search.par
> +        additive_sinogram :=
Should provide data (from another demo)

2021-05-26 21:23 UTC, robbietuk commented on examples/C++/src/demo5_line_search.par
> +    use exponential alphas := 1
does `exponential alphas` make sense?

2021-05-28 14:44 UTC, KrisThielemans reviewed
some comments. I haven't checked the actual .cxx file

2021-05-28 14:44 UTC, KrisThielemans commented on examples/C++/src/demo5_line_search.par
> +    use exponential alphas := 1
sure. and it's just a demo

2021-05-28 14:44 UTC, KrisThielemans commented on examples/C++/src/demo5_line_search.par
> +    alpha max := -2   ; default: 1.0
?

2021-06-04 19:41 UTC, KrisThielemans requested changes

2021-06-04 19:41 UTC, KrisThielemans commented on examples/C++/src/demo5_line_search.cxx
> +  Additionally, a lower positivity bound is applied to all computed image.
```suggestion
```suggestion
  from a minimum to a maximum step size (alpha).
  Options are included to perform this line search linearly or using exponential step
  sizes.
  Additionally, a lower positivity bound is applied to all computed images.
```

2021-06-04 20:13 UTC, merged