Modification on test_IO.m and test_buildblock.m
UCL/STIR pull request #923
Opened 2021-09-07 13:10 UTC by luciferlys

In these two test files, function 'isequal' is used in some places and that would throw out errors because of possible conflicts with the current version of STIR. So I just replaced all 'isequal' by 'eq', which probably has the same feature and work well with current STIR. Now the these two tests can be run successfully without any errors.

2021-09-07 14:06 UTC, KrisThielemans requested changes
I'm not sure how you got changes in other files (or even commits) in this PR. I guess you could either create a new PR with only changes in the .m files, or revert the other files to their current version on `master`

2021-09-07 15:42 UTC, luciferlys commented
It's really strange. I only git add these two test files. I'll try to revert the other files to their current version.

2021-09-07 16:04 UTC, luciferlys commented
I checked again. It seems like these two files are not modified by me. In 'master' branch, they're modified 5 months ago. However, in the branch I just created they are modified 4 months ago with the commit message made by you 'release 4.1.1'. I really have no idea why it is.

2021-09-07 18:36 UTC, KrisThielemans commented
hmm. I suppose your started from a 4.1.1 checkout then. still surprises me, but fine.

let's try the following
```
git fetch origin
git rebase origin/master
```
with any luck, you won't have conflicts, and there will be only 1 commit remaining (on top of what is current `master`). If that works (and `git diff origin/master` just shows your changes only), then do
```
git push --force yourfork lys_stir
```
(replacing `yourfork` with how you called your fork as remote).

If it descends into a nightmare, you can do
```
git rebase --abort
```
I would then suggest to start from scratch and say
```
git checkout origin/master
git checkout -b lys_stir_swig
# just pick "your" commit
git cherry-pick 457681d079c5da1e167d4594f3a9444655cddfe8
git log
```
if that all looks fine, you can still push that to this PR (somewhat confusingly) by doing
```
git push --force yourfork lys_stir_swig:lys_stir
```

Or as opposed to doing the cherry-pick, you can just copy the files of course, and just create a new PR.

2021-09-22 10:14 UTC, KrisThielemans commented
Abandoned in favour of #929

2021-09-22 10:14 UTC, closed without merging