Use forward projector parfile with calculate_attenuation_coefficients utility.
UCL/STIR pull request #928
Opened 2021-09-15 16:18 UTC by HTunne

Add an optional extra argument to 'calculate_attenuation_coefficients' utility to allow the use of a parameter file to describe the forward projector to use. The parameter file follows the format of the 'forward_project' utility.

This has been useful to allow caching to be disabled when working with large system matrices (particularly for block geometries).

2021-09-22 16:23 UTC, HTunne commented
Hi @robbietuk, yep, had my editor set to remove trailing whitespace. Just cleaned up some of the unnecessary changes and added the suggested example usage to the `recon_test_pack`

2021-09-22 19:11 UTC, KrisThielemans requested changes
looks great. Thanks. Let's wait for Appveyor. I found just a tiny spelling mistake. Please commit that with `[ci skip]` in the commit message.

2021-09-22 19:11 UTC, KrisThielemans commented on src/utilities/calculate_attenuation_coefficients.cxx
> +  \par Optionially include parameter file for specifying the forward projector (overrules --PMRT and --NOPMRT options)
```suggestion
  \par Optionally include a parameter file for specifying the forward projector (overrules --PMRT and --NOPMRT options)
```

2021-09-24 11:03 UTC, KrisThielemans approved these changes

2021-09-24 11:04 UTC, merged

2021-09-24 11:06 UTC, KrisThielemans commented
oops. I forgot to ask you to add a line in `release_5.0.htm`. Can you do a new PR for that. sorry!

2021-09-24 11:46 UTC, HTunne commented
> oops. I forgot to ask you to add a line in `release_5.0.htm`. Can you do a new PR for that. sorry!

Hi Kris, I'll add that now. I presume it should go under the 'New functionality' sub-heading?