Plotting sinogram profile script
UCL/STIR pull request #934
Opened 2021-10-01 16:58 UTC by robbietuk

This is a STIR modified version of the script currently in [SIRF](https://github.com/SyneRBI/SIRF/blob/master/examples/Python/PET/PET_plot_functions.py).

Let me know if you want any in code references to the SIRF function.

2021-10-01 17:19 UTC, robbietuk commented
Also `[ci-skip]` because no tested changes were made.

2021-10-03 12:26 UTC, KrisThielemans requested changes
an attempt to make this useful as a module (haven't tried it)

2021-10-03 12:26 UTC, KrisThielemans commented on examples/python/plot_sinogram_profiles.py
> +                        help="Sum all elementsan axis (0,1 or 2).")
```suggestion
                        help="Sum all elements on axis (0,1 or 2).")
```

2021-10-03 12:26 UTC, KrisThielemans commented on examples/python/plot_sinogram_profiles.py
> +    filenames: sinogram filenames list to load and plot
```suggestion
    filenames: list of sinogram filenames or stir.ProjData objects to load and plot
```

2021-10-03 12:26 UTC, KrisThielemans commented on examples/python/plot_sinogram_profiles.py
> +        plt.plot(np.sum(prompts, axis=sumaxis)[select,:], label=f)
```suggestion
    for f in filenames:
        if isinstance(f, str):
            print(f"Handling:\n  {f}")
            f = stir.ProjData_read_from_file(f)
            label = f
        if isinstance(f, stir.ProjData):
            f = stirextra.to_numpy(f)
            label = ""
        else:
            raise ValueError("wrong type of argument")

        plt.plot(np.sum(f, axis=sumaxis)[select,:], label=label)
```

2021-10-03 12:26 UTC, KrisThielemans commented on examples/python/plot_sinogram_profiles.py
> +
```suggestion
# Or of course
#  import plot_sinogram_profiles
```

2021-10-03 16:17 UTC, robbietuk commented
I think this is ready now.

2021-10-03 18:20 UTC, merged